[package]
name = "keycloak"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
reqwest = "0.12.24"
serde_json = "1.0.141"
base64 = "0.21"
